# Usa una imagen base con Node.js
FROM node:14

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json (o yarn.lock) a la imagen
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de tu aplicación al directorio de trabajo
COPY . .

# Expone el puerto en el que tu aplicación se ejecutará (ajusta esto según tus necesidades)
EXPOSE 3000

# Comando para ejecutar tu aplicación
CMD ["npm", "start"]